name: Main

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        id: hello
        uses: yuler/test-create-github-action@v1.0.0
        with:
          who-to-greet: 'yuler'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

  local_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello world action step
        id: hello
        uses: ./
        with:
          who-to-greet: 'yuler'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
